FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 10000

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["app-prueba-1.csproj", "./"]
RUN dotnet restore "app-prueba-1.csproj"
COPY . .
RUN dotnet build "app-prueba-1.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "app-prueba-1.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "app-prueba-1.dll"]